'use strict';Object.defineProperty(exports,"__esModule",{value:true});exports.map=undefined;var _promise=require('babel-runtime/core-js/promise');var _promise2=_interopRequireDefault(_promise);var _regenerator=require('babel-runtime/regenerator');var _regenerator2=_interopRequireDefault(_regenerator);var _objectWithoutProperties2=require('babel-runtime/helpers/objectWithoutProperties');var _objectWithoutProperties3=_interopRequireDefault(_objectWithoutProperties2);var _asyncToGenerator2=require('babel-runtime/helpers/asyncToGenerator');var _asyncToGenerator3=_interopRequireDefault(_asyncToGenerator2);var _extends2=require('babel-runtime/helpers/extends');var _extends3=_interopRequireDefault(_extends2);var _map=require('babel-runtime/core-js/map');var _map2=_interopRequireDefault(_map);exports.default=function(_ref){var _this=this;var iteration=_ref.iteration,scenario=_ref.scenario,_ref$timestamp=_ref.timestamp,timestamp=_ref$timestamp===undefined?new Date():_ref$timestamp,client=_ref.client;var onNetworkRequestWillBeSent=function onNetworkRequestWillBeSent(_ref2){var requestId=_ref2.requestId,request=_ref2.request;if(!map.has(requestId)){map.set(requestId,{iteration:iteration,scenario:scenario,timestamp:timestamp,request:request});/*
      Logger.info(chalk.cyan('Network.requestWillBeSent'), '\n', {
        requestId,
        url: transformUrl(url),
        method
      }); */}};var onNetworkResponseReceived=function onNetworkResponseReceived(_ref3){var requestId=_ref3.requestId,response=_ref3.response;if(map.has(requestId)){map.set(requestId,(0,_extends3.default)({},map.get(requestId),{response:(0,_extends3.default)({requestId:requestId},response)}));/*
      Logger.info(chalk.cyan('Network.responseReceived'), '\n', {
        requestId,
        url: transformUrl(url),
        status,
        statusText
      }); */}};var onNetworkLoadingFailed=function(){var _ref4=(0,_asyncToGenerator3.default)(/*#__PURE__*/_regenerator2.default.mark(function _callee(){var _ref5=arguments.length>0&&arguments[0]!==undefined?arguments[0]:{};var requestId=_ref5.requestId,failed=(0,_objectWithoutProperties3.default)(_ref5,['requestId']);return _regenerator2.default.wrap(function _callee$(_context){while(1){switch(_context.prev=_context.next){case 0:if(map.has(requestId)){map.set(requestId,(0,_extends3.default)({},map.get(requestId),{failed:(0,_extends3.default)({requestId:requestId},failed)}));// Logger.info(chalk.red('Network.loadingFailed'), '\n', { ...failed, requestId });
}case 1:case'end':return _context.stop();}}},_callee,_this);}));return function onNetworkLoadingFailed(){return _ref4.apply(this,arguments);};}();var onNetworkLoadingFinished=function onNetworkLoadingFinished(_ref6){var requestId=_ref6.requestId,finished=(0,_objectWithoutProperties3.default)(_ref6,['requestId']);if(map.has(requestId)){map.set(requestId,(0,_extends3.default)({},map.get(requestId),{finished:(0,_extends3.default)({requestId:requestId},finished)}));// Logger.info(chalk.cyan('Network.loadingFinished'), '\n', { ...finished, requestId });
}};var attach=function attach(){return _promise2.default.resolve().then(function(){client.on('Network.requestWillBeSent',onNetworkRequestWillBeSent);client.on('Network.responseReceived',onNetworkResponseReceived);client.on('Network.loadingFailed',onNetworkLoadingFailed);client.on('Network.loadingFinished',onNetworkLoadingFinished);}).then(function(){return client.send('Network.enable');}).catch(function(_ref7){var _ref7$message=_ref7.message,message=_ref7$message===undefined?'No error message is defined':_ref7$message;_logger2.default.error(message);});};var detach=function detach(){return _promise2.default.resolve().then(function(){client.removeListener('Network.requestWillBeSent',onNetworkRequestWillBeSent);client.removeListener('Network.responseReceived',onNetworkResponseReceived);client.removeListener('Network.loadingFailed',onNetworkLoadingFailed);client.removeListener('Network.loadingFinished',onNetworkLoadingFinished);}).then(function(){return client.send('Network.disable');}).catch(function(_ref8){var _ref8$message=_ref8.message,message=_ref8$message===undefined?'No error message is defined':_ref8$message;_logger2.default.error(message);});};return{attach:attach,detach:detach};};var _logger=require('../../logger');var _logger2=_interopRequireDefault(_logger);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}// import transformUrl from 'app/transform-url';
var map=exports.map=new _map2.default();// import chalk from 'chalk';